# Generated by Django 6.0 on 2026-01-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_cliente_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo do produto', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço de venda', max_digits=10),
        ),
    ]
