# Generated by Django 6.0 on 2026-01-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_custo_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={},
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('DIN', 'Dinheiro'), ('CAR', 'Cartão'), ('PIX', 'PIX'), ('FIA', 'Fiado')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='paga',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='quitada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
