git ad# Generated by Django 6.0.1 on 2026-03-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fator_estoque',
            field=models.PositiveSmallIntegerField(default=1, help_text='Unidades do estoque consumidas por item vendido. Ex: fatia de pizza = 1, pizza inteira = 6.', verbose_name='Fator de estoque'),
        ),
        migrations.AddField(
            model_name='produto',
            name='produto_estoque',
            field=models.ForeignKey(blank=True, help_text='Produto cujo estoque será consumido ao vender este item. Deixe em branco para usar o próprio estoque.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes', to='core.produto', verbose_name='Produto de estoque'),
        ),
    ]
